[email]
# SMTP Gmail (exemple)  -> pour Outlook 365, vois plus bas
host = "smtp.gmail.com"
port = 587
user = "station.ferment@gmail.com"
password = "***"
sender = "station.ferment@gmail.com"

# optionnel : destinataires par défaut
recipients = ["***"]
